### ISSUE TITLE
NodeJS 6 is no longer maintained warning

### ISSUE THREAD

**Issue by paour** [JetBrains/upsource-with-tools-docker#5]
During install, NodeJS displays a prominent warning about the end of support for NodeJS 6. It's no longer the latest LTS version claimed by the readme 😄 .

I'm not sure what impact this has, if any, but it would probably be a good idea to review this script for obsolescence.

**Comment by abarsov** [comment]
Thanks for the warning notice! 
updated node version to the latest LTS

**Comment by paour** [comment]
Thanks for the speedy turn-around. Don't forget to update the readme.
